[package]
name = "digs"
description = "digs many at once"
version = "0.1.2"
authors = ["azzamsa <azzam@biznetgio.com>"]
categories = ["command-line-utilities"]
edition = "2018"
license = "GPLv3"
exclude = ["/README.md"]

[profile.release]
opt-level = 'z'  # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
anyhow = "1.0.40"
colored = "2.0.0"
clap = "3.0.0-beta.2"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.125", features = ["derive"] }
thiserror = "1.0.24"
toml = "0.5.8"
trust-dns-client = "0.20.0"

[dev-dependencies]
assert_cmd = "1.0.3"
predicates = "1.0.7"


