[package]
name = "digs"
version = "0.3.1"
authors = ["azzamsa <azzam@biznetgio.com>"]
categories = ["command-line-utilities"]
edition = "2018"
exclude = ["/README.md"]
keywords = ["cli", "dns", "dig"]
license = "GPL-3.0-only"
repository = "https://github.com/BiznetGIO/digs"
rust-version = "1.76.0"
description = "digs many at once"

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
hickory-client = "0.24.0"

clap = { version = "4.4.11", features = ["suggestions", "color", "cargo", "derive"] }
log = "0.4.20"
miette = { version = "5.10", features = ["fancy"] }
owo-colors = "3"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0"
toml = "0.8.8"

[dev-dependencies]
assert_cmd = "2.0.12"
assert_fs = "1.0.13"
predicates = "3.0.4"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version}-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.release]
sign-commit = true
sign-tag = true
tag-message = "v{{version}}"
pre-release-commit-message = "v{{version}}"
pre-release-hook = ["just", "_release-prepare", "{{version}}"]
