[package]
name = "digs"
version = "0.1.7"
authors = ["azzamsa <azzam@biznetgio.com>"]
categories = ["command-line-utilities"]
edition = "2018"
exclude = ["/README.md"]
keywords = ["cli", "dns", "dig"]
license = "GPL-3.0-only"
repository = "https://github.com/BiznetGIO/digs"
description = "digs many at once"

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
colored = "2.0"
log = "0.4"
miette = { version = "5.5", features = ["fancy"] }
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.5"
trust-dns-client = "0.22"

[dependencies.clap]
version = "4.0"
features = ["suggestions", "color", "cargo", "derive"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
