[package]
name = "digs"
version = "0.1.7"
authors = ["azzamsa <azzam@biznetgio.com>"]
categories = ["command-line-utilities"]
edition = "2018"
exclude = ["/README.md"]
keywords = ["cli", "dns", "dig"]
license = "GPL-3.0-only"
repository = "https://github.com/BiznetGIO/digs"
description = "digs many at once"

[profile.release]
opt-level = 'z' # Optimize for size.
codegen-units = 1
lto = true
panic = 'abort'

[dependencies]
anyhow = "1.0.40"
clap = { version = "3.1.18", features = ["suggestions", "cargo"] }
colored = "2.0.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.125", features = ["derive"] }
thiserror = "1.0.24"
toml = "0.5.8"
trust-dns-client = "0.20.0"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
