[[servers]]
ip = "1.0.0.1"
name = "Cloudflare"

[[servers]]
ip = "8.8.8.8"
name = "Google"

[[servers]]
ip = "8.8.4.4"
name = "Google 1"

[[servers]]
ip = "9.9.9.9"
name = "Quad9"

[[servers]]
ip = "149.112.112.112"
name = "Quad9 1"

[[servers]]
ip = "208.67.222.222"
name = "Cisco"

[[servers]]
ip = "208.67.220.220"
name = "Cisco 1"

[[servers]]
ip = "208.67.222.222"
name = "OpenDNS"

[[servers]]
ip = "208.67.220.220"
name = "OpenDNS 1"

[[servers]]
ip = "8.26.56.26"
name = "Comodo DNS"

[[servers]]
ip = "8.20.247.20"
name = "Comodo DNS 1"

[[servers]]
ip = "64.6.64.6"
name = "Verysign"

[[servers]]
ip = "64.6.65.6"
name = "Verysign 1"

[[servers]]
ip = "77.88.8.3"
name = "Yandex"

[[servers]]
ip = "77.88.8.7"
name = "Yandex"

[[servers]]
ip = "94.140.14.14"
name = "AdGuard"

[[servers]]
ip = "94.140.14.15"
name = "AdGuard"

[[servers]]
ip = "185.228.168.168"
name = "CleanBrowsing"

[[servers]]
ip = "185.228.169.168"
name = "CleanBrowsing 1"
